baseURL = "http://aaanu.github.io/"
languageCode = "en-us"
title = "Anu Gulati"
theme="cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Anu Gulati"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Anu Gulati"
logofile = "https://images.genius.com/8a23b87972751c2fdadaf4837b6a2930.355x355x1.jpg"
faviconfile = "https://i.pinimg.com/originals/16/bb/7e/16bb7ee21252810d449538e46a329c04.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "aaanu"
email = "anu.gulati100@gmail.com"
linkedin = "anuradhagulati"
twitter = "aaaaaanu"
instagram="kungfuanu"
lastfm="aaaaanu"
letterboxd="anuuu"
soundcloud="anu-gulati"
bandcamp="anuuu"
social_banner = ""
posts_navigation = true
small_banner_logo = false